# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "test-docker"
  config.vm.box_check_update = false

  # Redirect port for Docker
  config.vm.network "forwarded_port", guest: 2375, host: 8089, host_ip: "127.0.0.1"

  # Configure VM several parameters
   config.vm.provider "virtualbox" do |vb|
     vb.name = "test-docker"

     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "512"
   end

  # Enable provisioning with a shell script for install Docker and configure API.

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    sudo sed -i 's_^ExecStart=.*_& -H=tcp://0.0.0.0:2375_' /lib/systemd/system/docker.service
    sudo systemctl daemon-reload
    sudo service docker restart
  SHELL
end
